export const policiaEvents = [
    {
        year: "1894",
        text: "Fundación de la Policía Urbana de Santander, compuesta por ocho agentes y un cabo. Se instala su oficina en los soportales del Ayuntamiento de la Plaza Vega.",
        image: "/images/policia/1894Policia.jpg",
        source: "La Nueva España",
    },
    {
        year: "1896",
        text: "Segundo Reglamento. Se implanta la denominación oficial 'GUARDIA MUNICIPAL', compuesta por 25 monitores, 2 Cabos y un jefe.",
        image: "/images/policia/1896Policia.jpg",
        source: "La Razón",
    },
    {
        year: "1898",
        text: "Tercer Reglamento. Se adjunta un anexo con nuevos formularios de denuncias y sanciones uniformes.",
        image: "/images/policia/1898Policia.jpg",
        source: "Faro de Vigo",
    },
    {
        year: "1899",
        text: "Año trágico para la ciudad y la Guardia Municipal: 40 agentes y el Jefe del Cuerpo, D. Marcelino ROMAY FERNÁNDEZ, fallecen en la catástrofe del 'Cabo Machichaco'.",
        image: "/images/policia/1899Policia.jpg",
        source: "National Geographic",
    },
    {
        year: "1900",
        text: "Unificación de las secciones nocturna y diurna, que hasta esta fecha habían funcionado de modo independiente.",
        image: "/images/policia/1900Policia.jpg",
        source: "Policia Local de Murcia",
    },
    {
        year: "1902",
        text: "Cuarto Reglamento. Por primera vez, se recogen las funciones de la Guardia Municipal como parte de la Policía Social y Gobernativa. La plantilla cuenta con 42 agentes.",
        image: "/images/policia/1902Policia.jpg",
        source: "La voz del Sur",
    },
    {
        year: "1908",
        text: "Quinto Reglamento para el Cuerpo. En julio, se nombra jefe a D. Manuel NÚÑEZ GONZÁLEZ, Teniente de Carabineros, quien se jubila en 1946.",
        image: "/images/policia/1908Policia.jpg",
        source: "Ayuntamiento de Zaragoza",
    },
    {
        year: "1934",
        text: "La Guardia Municipal cumple 100 años. La componen 1 Jefe, 9 Cabos y 18 Guardias.",
        image: "/images/policia/1934Policia.jpg",
        source: "Cadena SER",
    },
    {
        year: "1941",
        text: "Incendio de Santander. La Guardia Municipal trabaja incansablemente rescatando a numerosas personas de perecer calcinadas.",
        image: "/images/policia/1941Policia.jpg",
        source: "El Diario",
    },
    {
        year: "1956",
        text: "Sexto Reglamento. Establece la denominación oficial de 'POLICÍA MUNICIPAL'.",
        image: "/images/policia/1956Policia.jpg",
        source: "Diario Sur",
    },
    {
        year: "1961",
        text: "Incorporación de la mujer a la Policía Local de Santander.",
        image: "/images/policia/1961Policia.jpg",
        source: "Diario de Córdoba",
    },
    {
        year: "1979",
        text: "Se implanta en la ciudad la 'Zona Azul' como un sistema de distribución más equitativa de las plazas de estacionamiento en las calles más céntricas. El Alcalde es D. Marino FERNÁNDEZ REGATILLO Y BASATE.",
        image: "/images/policia/1979Policia.jpg",
        source: "Archivo de Mallorca",
    },
    {
        year: "1998",
        text: "Inauguración del nuevo edificio que alberga las instalaciones de la Policía Local de Santander, incluyendo una exposición histórica con documentos y fotografías que recogen más de un siglo de historia.",
        image: "/images/policia/1998Policia.jpg",
        source: "Todocolección",
    },
];