export const reportajesSalvamentoMaritimo = [
    {
      id: 1,
      titulo: "Lo más peligroso del mar y sus superhéroes",
      autores: ["Pablo Vázquez", "Sofía Toraya"],
      subtitulo: "En las costas del país peninsular hay puntos donde el mar no concede ningún tipo de tregua con los trabajadores de salvamento marítimo. El clima de estas zonas, la gran cantidad de tráfico o las rutas migratorias en pequeñas embarcaciones hace que en cualquier momento ocurra un suceso. Desde el mar revuelto y agresivo del Atlántico hasta las profundas aguas calientes llenas de fauna y flora de Canarias. Los equipos ponen constantemente su vida en peligro para proteger las vidas humanas de las personas que se lanzan al mar. Este reportaje trata de enseñar a los desconocedores de estas zonas muy activas y peligrosas para que la gente sepa que hacer y así no arriesgar su vida y la de los trabajadores de salvamento marítimo.",
     
    },
    // {
    //   id: 2,
    //   titulo: "Bomberos: Valor y Vocación",
    //   autores: ["Pablo Vázquez", "Sofía Toraya"],
    //   subtitulo: "La razón, por la cual el día del bombero se celebra el día 4 de mayo en la mayoría de lugares del mundo",
    //   foto: "public/reportajes/bomberos/Rep_Bomberos_02.jpg",
    // },
    // {
    //   id: 3,
    //   titulo: "La explosión química del puerto",
    //   autores: ["Miguel Ríos", "Claudia Alonso"],
    //   subtitulo: "Cuando la niebla ocultó la tragedia",
    //   foto: "/Reportajes/Bomberos/quimico.jpg",
    // },
    // {
    //   id: 4,
    //   titulo: "Un rescate entre las llamas",
    //   autores: ["Andrea López"],
    //   subtitulo: "Testimonio de un bombero veterano",
    //   foto: "/Reportajes/Bomberos/rescate.jpg",
    // },
    // {
    //   id: 5,
    //   titulo: "El bosque arde",
    //   autores: ["Luis Gómez"],
    //   subtitulo: "La lucha por salvar el Parque Natural de Peña Sagra",
    //   foto: "/Reportajes/Bomberos/bosque.jpg",
    // },
    // {
    //   id: 6,
    //   titulo: "La llamada a medianoche",
    //   autores: ["Sergio Jiménez", "Nuria Ferrer"],
    //   subtitulo: "Emergencia en una residencia de ancianos",
    //   foto: "/Reportajes/Bomberos/noche.jpg",
    // },
    // {
    //   id: 7,
    //   titulo: "Incendio en la nave industrial",
    //   autores: ["Paula Castaño"],
    //   subtitulo: "Pánico y reacción inmediata",
    //   foto: "/Reportajes/Bomberos/nave.jpg",
    // },
    // {
    //   id: 8,
    //   titulo: "Fuego en los acantilados",
    //   autores: ["Héctor Ruiz"],
    //   subtitulo: "Dificultades en el acceso y el viento marino",
    //   foto: "/Reportajes/Bomberos/acantilado.jpg",
    // },
    // {
    //   id: 9,
    //   titulo: "El simulacro que salvó vidas",
    //   autores: ["Elena Torres"],
    //   subtitulo: "Prevención eficaz antes del desastre real",
    //   foto: "/Reportajes/Bomberos/simulacro.jpg",
    // },
    // {
    //   id: 10,
    //   titulo: "Crónica de una intervención urbana",
    //   autores: ["Raúl Nieto"],
    //   subtitulo: "Un coche ardiendo en el centro de la ciudad",
    //   foto: "/Reportajes/Bomberos/urbano.jpg",
    // },
    // {
    //     id: 11,
    //     titulo: "Crónica de una intervención urbana",
    //     autores: ["Raúl Nieto"],
    //     subtitulo: "Un coche ardiendo en el centro de la ciudad",
    //     foto: "/Reportajes/Bomberos/urbano.jpg",
    //   },
  ];
  